"""Replay buffer for self-play training data.

AlphaZero's training data is not i.i.d. — it's a stream of position–
visit-distribution–outcome triples generated by self-play. The buffer keeps
a sliding window of recent examples; the trainer samples random minibatches
from it for SGD.

Two design choices worth pinning down:

1. **FIFO eviction over a fixed capacity** (deque semantics). Why not a
   uniform sample over all history? Because the network distribution shifts
   as training progresses — old games were generated by a much weaker net
   and their visit distributions are *off-policy*. A window keeps data
   roughly on-policy.

2. **Sample without replacement within a single batch.** Standard practice;
   reduces gradient variance vs. with-replacement at small batch sizes.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Iterable

import numpy as np


@dataclass
class TrainingExample:
    """One supervision triple from self-play.

    encoded_state: float32 array, shape `(C, H, W)`. The result of
        `Game.encode(state)` — already from the to-move player's perspective.
    policy_target: float32 array, shape `(action_size,)`. The normalised
        MCTS visit distribution at this state. Sums to 1. *This is the
        amplified policy* — MCTS-with-search is provably stronger than the
        network's raw policy, and that strength is what we distill.
    value_target: scalar in [-1, +1]. The eventual game outcome from this
        position's to-move player's perspective. +1 if they went on to win,
        -1 if they lost, 0 for a draw.
    """

    encoded_state: np.ndarray
    policy_target: np.ndarray
    value_target: float


class ReplayBuffer:
    """Fixed-capacity FIFO buffer of TrainingExamples."""

    def __init__(self, capacity: int, seed: int | None = None) -> None:
        if capacity < 1:
            raise ValueError("capacity must be >= 1")
        self.capacity = capacity
        self._buf: deque[TrainingExample] = deque(maxlen=capacity)
        self.rng = np.random.default_rng(seed)

    def __len__(self) -> int:
        return len(self._buf)

    def add(self, example: TrainingExample) -> None:
        self._buf.append(example)

    def extend(self, examples: Iterable[TrainingExample]) -> None:
        self._buf.extend(examples)

    def sample(self, batch_size: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Sample a random batch as stacked numpy arrays, no replacement.

        Returns:
            states:   (B, C, H, W) float32
            policies: (B, action_size) float32
            values:   (B,) float32
        """
        if batch_size < 1:
            raise ValueError("batch_size must be >= 1")
        if len(self._buf) < batch_size:
            raise ValueError(
                f"buffer has {len(self._buf)} examples; need {batch_size}"
            )

        indices = self.rng.choice(len(self._buf), size=batch_size, replace=False)
        examples = [self._buf[int(i)] for i in indices]
        states = np.stack([e.encoded_state for e in examples]).astype(np.float32)
        policies = np.stack([e.policy_target for e in examples]).astype(np.float32)
        values = np.array([e.value_target for e in examples], dtype=np.float32)
        return states, policies, values
